apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-deploy
  template:
    metadata:
      name: app-deploy
      labels:
        app: app-deploy
    spec:
      containers:
      - name: app
        image: jaibw/api
        ports:
        - containerPort: 8081 
        env: 
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
        - name: DBUSER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DBUSER
        - name: DBHOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DBHOST
        - name: DBPORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DBPORT
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DBNAME
