apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  namespace: production
spec:
  storageClassName: manual
  volumeName: pv-postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi